version: "3.9"

volumes:
    database:
      external: true

services:
  digital-wallet-2-database:
    platform: linux/amd64
    container_name: digital-wallet-2-database
    restart: always
    image: mysql:5.7
    volumes:
      - .database:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"

  digital-wallet-2-redis:
    container_name: digital-wallet-2-redis
    image: redis
    command: redis-server --requirepass 1234
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - .redis:/var/lib/postgresql/data

  digital-wallet-2-collect:
    platform: linux/amd64
    container_name: digital-wallet-2-collect
    image: apiovani/golang-digital-walleet:lastest
    # build: .
    volumes:
      - .:/go/src/
    ports:
      - 8081:8080
    depends_on:
      - "digital-wallet-2-redis"
    command: ./service collect
    env_file:
      - .env

  digital-wallet-2-api:
    platform: linux/amd64
    container_name: digital-wallet-2-api
    image: apiovani/golang-digital-walleet:lastest
    # build: .
    volumes:
      - .:/go/src/
    ports:
      - 8080:8080
    depends_on:
      - "digital-wallet-2-redis"
      - "digital-wallet-2-database"
    command: ./service api
    env_file:
      - .env
    
  digital-wallet-2-prometheus:
    platform: linux/amd64
    container_name: digital-wallet-2-prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    command: --config.file=/etc/prometheus/prometheus.yml

  digital-wallet-2-pushgateway:
    platform: linux/amd64
    container_name: digital-wallet-2-pushgateway
    image: prom/pushgateway
    expose:
      - 9091
    ports:
      - 9091:9091
    depends_on:
      - digital-wallet-2-prometheus
  
  digital-wallet-2-grafana:
    platform: linux/amd64
    container_name: digital-wallet-2-grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - digital-wallet-2-prometheus
      - digital-wallet-2-pushgateway
    